In [31]:
import numpy as np
np.random.seed(10)
A = np.random.rand(9,9,9)+0.1
B = np.random.rand(1,9)+0.3

In [48]:
A = np.matrix.round(A, decimals=4)
B = np.matrix.round(B, decimals=4)

In [53]:
x = np.inner(A,B)
print(x.shape)

(9, 9, 1)


In [54]:
x[3,4]

array([3.74243378])

In [56]:
x = np.matrix.round(x, decimals=4)

In [59]:
x[5,4]

array([3.6948])

In [62]:
x[5,4], x[4,5]

(array([3.6948]), array([4.585]))

In [10]:
p = [0.2,0.2,0.2,0.2,0.2]
import numpy as np
pp = np.array([p,p,p])

In [21]:
ppp = np.random.rand(9,9,9)
ppp.shape

(9, 9, 9)

In [13]:
pp.shape

(3, 5)

In [23]:
from scipy.stats import entropy
entropy(ppp).shape

(9, 9)